services:
  host:
    build: ./host
    ports:
      - "8080:8080"  
    depends_on:
      - content  
    environment:
      - CONTENT_SERVICE_URL=http://content:8081  
    networks:
      - frontend

  content:
    build: ./content
    ports:
      - "8081:8081" 
    networks:
      - frontend

networks:
  frontend:
    driver: bridge

